version: "3.8"

networks:
  default:
    name: unifi

volumes:
  mongodb:
    name: unifi-mongodb
  network-application:
    name: unifi-network-application

services:

  mongodb:
    image: mongo:5.0
    container_name: unifi-mongodb
    volumes:
      - type: volume
        source: mongodb
        target: /data/db
#      - type: bind
#        read_only: true
#        source: ./admin.sh
#        target: /docker-entrypoint-initdb.d/admin.sh
#      - type: bind
#        read_only: true
#        source: ./entrypoint.sh
#        target: /entrypoint.sh
#    entrypoint:
#      - /entrypoint.sh
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-admin}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-unifi}
      # Not used by the base MongoDB image but by the custom init scripts
      MONGO_DB_USER: ${MONGO_DB_USER:-unifi}
      MONGO_DB_PASS: ${MONGO_DB_PASS:-unifi}

  application:
    depends_on:
      - mongodb
    image: ghcr.io/stellirin/unifi-network-application:${CONTROLLER_IMAGE_TAG:-latest}
    container_name: unifi-network-application
    ports:
      # UniFi
      - "1900:1900/udp"
      - "3478:3478/udp"
      - "5514:5514/udp"
      - "6789:6789/tcp"
      - "8080:8080/tcp"
      - "8443:8443/tcp"
      - "10001:10001/udp"
      # Portal
      - "8880:8880/tcp"
      - "8881:8881/tcp"
      - "8882:8882/tcp"
      - "8843:8843/tcp"
    volumes:
      - type: volume
        source: network-application
        target: /var/lib/unifi
    environment:
      MONGO_DB_HOST: ${MONGO_DB_HOST:-mongodb}
      MONGO_DB_PORT: ${MONGO_DB_PORT:-27017}
      MONGO_DB_USER: ${MONGO_DB_USER:-unifi}
      MONGO_DB_PASS: ${MONGO_DB_PASS:-unifi}
      JAVA_TOOL_OPTIONS: "--add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.time=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED"
