apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - persistent-volume-claim.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - certificate.yaml
  - ingress-route.yaml
