apiVersion: v1
kind: Secret
metadata:
  namespace: mongodb
  name: unifi
stringData:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "admin"
  # Not used by the base MongoDB image but by the custom init scripts
  MONGO_DB_USER: "unifi"
  MONGO_DB_PASS: "unifi"
