apiVersion: v1
kind: Service
metadata:
  namespace: mongodb
  name: mongodb-7
  labels:
    app: mongodb-7
spec:
  type: ClusterIP
  selector:
    app: mongodb-7
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
    targetPort: mongo
